services:
  backend:
    container_name: floehire-backend
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/floehire
      - PRISMA_CLIENT_ENGINE_TYPE=binary
    depends_on:
      - database

  database:
    container_name: floehire-db
    image: postgres:15
    environment:
      POSTGRES_DB: floehire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
